baseURL = 'https://unburdened.biz/'
languageCode = 'en-us'
title = 'Unburdened'

[security]
  [security.funcs]
    getenv = ['^ENVIRONMENT$']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
